### ISSUE TITLE
add_numeric not recording answer

### ISSUE THREAD

**Issue by BriceonWiley** [priism-center/shinyQuiz#6]
I have a few shinyquizzes embedded within an HTML document. When I tried to operate one where the student has to give back a numeric answer, the value is not recorded.

I tried with both the regular numeric answer and with the slider to confirm that it was not taking in any answers that were not already predetermined ("add_choice()"). Have you had this issue before?

**Comment by joemarlo** [comment]
Hmm it is likely a namespace issue. Can you provide a reproducible example?

**Comment by BriceonWiley** [comment]
Thank you for pointing that out. I think things were getting lost in translation for me from over-utilizing an unnecessarily complicated template I had made for using the quizzes. When I simplified the shiny app considerably based on the example you all have on the package's homepage, I was able to get it to access the answers successfully.

**Comment by joemarlo** [comment]
Glad to hear you sorted it out!
